### ISSUE TITLE
Docker image doesn't start with UnsupportedClassVersionError

### ISSUE THREAD

**Issue by falko** [zeebe-io/zeebe-simple-monitor#104]
When trying to launch the latest docker image `camunda/zeebe-simple-monitor:0.17.0-alpha1` it produces the following exception:
```java
zeebe_monitor    | Exception in thread "main" java.lang.UnsupportedClassVersionError: io/zeebe/monitor/ZeebeSimpleMonitorApp has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
zeebe_monitor    | 	at java.lang.ClassLoader.defineClass1(Native Method)
zeebe_monitor    | 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
zeebe_monitor    | 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
zeebe_monitor    | 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
zeebe_monitor    | 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
zeebe_monitor    | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
zeebe_monitor    | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
zeebe_monitor    | 	at java.security.AccessController.doPrivileged(Native Method)
zeebe_monitor    | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
zeebe_monitor    | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
zeebe_monitor    | 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
zeebe_monitor    | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
zeebe_monitor    | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
zeebe_monitor    | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
zeebe_monitor    | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
zeebe_monitor    | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
zeebe_monitor exited with code 1
```

Here is the snippet from `docker-compose.yml`:
```yaml
  monitor:
    container_name: zeebe_monitor
    image: camunda/zeebe-simple-monitor:0.17.0-alpha1
    environment:
      - spring.datasource.url=jdbc:h2:tcp://db:1521/zeebe-monitor
      - io.zeebe.monitor.connectionString=zeebe:26500
      - io.zeebe.monitor.hazelcast.connection=zeebe:5701
    ports:
      - "8082:8080"
    depends_on:
      - db
      - zeebe
    restart: always
    networks:
      - zeebe_network
  db:
    image: oscarfonts/h2:1.4.197
    container_name: zeebe_db
    ports:
      - "1521:1521"
      - "81:81"
    networks:
      - zeebe_network
```

It sounds to me like the `zeebe-simple-monitor.jar` has been built with a new Java version, while the [docker image](https://github.com/zeebe-io/zeebe-simple-monitor/blob/master/app/Dockerfile) is based on `openjdk:8-jre-alpine`.
