### ISSUE TITLE
persistent database for zeebe monitor

### ISSUE THREAD

**Issue by bekbergenb** [zeebe-io/zeebe-simple-monitor#132]
Are there any way to save all bpmn schemes in database like Postgres, which will save all data even if the zeebe-monitor was rebooted/reloaded

**Comment by saig0** [comment]
If you're using **docker-compose** then you need to add the following configuration to the existing docker-compose file:

Zeebe Simple Monitor:
* environment: (connection to PostgreSQL)
```
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=zeebe
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
```

* volumes: (incude the PostgreSQL driver in the classpath)
```
      - ./lib/postgresql-42.2.12.jar:/app/libs/postgresql-42.2.12.jar
```

Add the PostgreSQL container:
```
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: zeebe
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - zeebe_network

volumes:
  database-data:
```

<details>
  <summary>docker-compose.yml</summary>
  <p>

```
version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:0.23.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ../target/exporter/zeebe-hazelcast-exporter.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network
  monitor:
    container_name: zeebe-simple-monitor
    image: camunda/zeebe-simple-monitor:latest
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.worker.hazelcast.connection=zeebe:5701
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=zeebe
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    volumes:
      - ./lib/postgresql-42.2.12.jar:/app/libs/postgresql-42.2.12.jar
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
      - db
    networks:
      - zeebe_network

  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: zeebe
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - zeebe_network

volumes:
  database-data:
```

  </p>
</details>

If you start the app **directly via Java** then the driver needs to be added to the classpath. For example: 
```
java -cp zeebe-simple-monitor-0.18.0.jar -Dloader.path="lib" org.springframework.boot.loader.PropertiesLauncher
```

@bekbergenb, does this work for you?
